clean_rollout_path = true
max_batch_size = 96

[monitor.wandb]
project = "math-debug"

[model]
name = "Qwen/Qwen2.5-1.5B-Instruct"
max_model_len = 1024

[data]
name = "/usr/workspace/venkatraman1/data/gsm8k-genesys/train"

[parallel]
dp = 6

[rl]
ckpt_path = "/usr/workspace/venkatraman1/checkpoints"
clean_ckpt_path = true